/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.49
</auto-generated>
------------------------------------------------------------------------------ */

using Newtonsoft.Json;
using SiteFInityWebApp.Mvc.ViewModels;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace SiteFInityWebApp.Mvc.Models
{
	public class FlightDataModel
	{
		public LaunchViewModel GetViewModel() => 
			Task.Run(() => this.GetLaunchAsync()).Result;


		private async Task<LaunchViewModel> GetLaunchAsync()
		{
			using (var client = new HttpClient())
			{
				var response = await client.
					GetAsync("https://api.spacexdata.com/v3/launches/Latest");
				response.EnsureSuccessStatusCode();
				var jsonString = await response.Content.ReadAsStringAsync();

				return JsonConvert.DeserializeObject<LaunchViewModel>(jsonString);

			}
		}
	}
}